import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import { createAdminClient } from '@/lib/supabase/admin'
import type { QuoteOutput, InvoiceOutput, EmailOutput } from '@/lib/types'
import { ViewActions } from './view-actions'
import { QuoteAcceptButton } from './quote-accept-button'
import { ExchangeRateHint } from '@/components/ui/exchange-rate-hint'

interface Props {
  params: Promise<{ id: string }>
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params
  const admin = createAdminClient()
  const { data: gen } = await admin
    .from('generations')
    .select('tool_type, output_data, locale, user_id')
    .eq('id', id)
    .single()

  if (!gen?.output_data) return { title: 'BizDoc AI' }

  const zh = (gen.locale ?? 'en') === 'zh'
  const out = gen.output_data as Record<string, unknown>

  const typeLabel: Record<string, string> = {
    quote:   zh ? '报价单' : 'Quotation',
    invoice: zh ? 'Invoice' : 'Invoice',
    email:   zh ? '商务邮件' : 'Business Email',
  }

  let title = typeLabel[gen.tool_type] ?? 'Document'
  let description = zh ? '由企文助手 AI 生成的专业商业文书' : 'Professional business document generated by BizDoc AI'

  if (gen.tool_type === 'quote') {
    const q = out as unknown as QuoteOutput
    title = q.title ?? title
    if (q.total && q.currency) description = `Total: ${new Intl.NumberFormat('en-US', { style: 'currency', currency: q.currency }).format(q.total)}`
  } else if (gen.tool_type === 'invoice') {
    const inv = out as unknown as InvoiceOutput
    title = `${typeLabel.invoice} #${inv.invoiceNumber}`
    if (inv.total && inv.currency) description = `${zh ? '总金额' : 'Amount Due'}: ${new Intl.NumberFormat('en-US', { style: 'currency', currency: inv.currency }).format(inv.total)}`
  } else if (gen.tool_type === 'email') {
    title = (out as unknown as EmailOutput).subject ?? title
  }

  const url = `${process.env.NEXT_PUBLIC_SITE_URL ?? ''}/view/${id}`

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      url,
      siteName: zh ? '企文助手' : 'BizDoc AI',
      type: 'website',
    },
    twitter: {
      card: 'summary',
      title,
      description,
    },
  }
}

function fmt(n: number, currency: string) {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency, minimumFractionDigits: 2 }).format(n)
}

function daysUntil(dateStr: string): number | null {
  if (!dateStr) return null
  const d = new Date(dateStr)
  if (isNaN(d.getTime())) return null
  return Math.ceil((d.getTime() - Date.now()) / 86400000)
}

function ValidityBanner({ validUntil, zh }: { validUntil?: string; zh: boolean }) {
  if (!validUntil) return null
  const days = daysUntil(validUntil)
  if (days === null) return null
  if (days > 7) return null
  const expired = days < 0
  return (
    <div className={`flex items-center gap-2 rounded-lg px-4 py-2.5 text-sm font-medium ${expired ? 'bg-red-50 text-red-700 border border-red-200' : 'bg-amber-50 text-amber-700 border border-amber-200'}`}>
      <span className="text-base">{expired ? '⚠️' : '⏰'}</span>
      {zh
        ? expired
          ? `此报价已于 ${validUntil} 过期`
          : `此报价将于 ${days} 天后（${validUntil}）过期`
        : expired
          ? `This quote expired on ${validUntil}`
          : `This quote expires in ${days} day${days === 1 ? '' : 's'} (${validUntil})`}
    </div>
  )
}

function InvoiceStatusPill({ status, zh }: { status?: string | null; zh: boolean }) {
  if (!status) return null
  const map: Record<string, { label: string; labelZh: string; cls: string }> = {
    pending:  { label: 'Payment Pending', labelZh: '待支付',  cls: 'bg-amber-100 text-amber-700 border-amber-200' },
    reminded: { label: 'Reminder Sent',   labelZh: '已提醒',  cls: 'bg-blue-100 text-blue-700 border-blue-200' },
    paid:     { label: 'Paid',            labelZh: '已付款',  cls: 'bg-emerald-100 text-emerald-700 border-emerald-200' },
    overdue:  { label: 'Overdue',         labelZh: '逾期未付', cls: 'bg-red-100 text-red-700 border-red-200' },
    cancelled:{ label: 'Cancelled',       labelZh: '已取消',  cls: 'bg-slate-100 text-slate-600 border-slate-200' },
  }
  const cfg = map[status]
  if (!cfg) return null
  return (
    <span className={`inline-flex items-center rounded-full border px-3 py-0.5 text-xs font-semibold ${cfg.cls}`}>
      {zh ? cfg.labelZh : cfg.label}
    </span>
  )
}

interface CompanyInfo {
  company_name: string | null
  contact_name: string | null
  email: string | null
  phone: string | null
  address: string | null
  logo_url: string | null
}

function DocumentHeader({ company, docTitle, docNumber, date, dueDate, status, zh }: {
  company: CompanyInfo | null
  docTitle: string
  docNumber?: string
  date?: string
  dueDate?: string
  status?: string | null
  zh: boolean
}) {
  return (
    <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-6 pb-8 border-b border-slate-100">
      {/* Left: company identity */}
      <div className="flex items-start gap-4">
        {company?.logo_url ? (
          <img src={company.logo_url} alt="logo" className="h-12 w-auto max-w-[140px] object-contain rounded" />
        ) : (
          <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-lg bg-indigo-600 text-white font-bold text-xl">
            {(company?.company_name ?? 'B').charAt(0).toUpperCase()}
          </div>
        )}
        <div className="space-y-0.5">
          {company?.company_name && <p className="font-bold text-slate-900 text-base">{company.company_name}</p>}
          {company?.contact_name && <p className="text-sm text-slate-500">{company.contact_name}</p>}
          {company?.email && <p className="text-xs text-slate-400">{company.email}</p>}
          {company?.phone && <p className="text-xs text-slate-400">{company.phone}</p>}
        </div>
      </div>

      {/* Right: document meta */}
      <div className="sm:text-right space-y-1.5">
        <div className="flex sm:justify-end items-center gap-2">
          <h2 className="text-xl font-bold text-slate-900">{docTitle}</h2>
          {status && <InvoiceStatusPill status={status} zh={zh} />}
        </div>
        {docNumber && <p className="text-sm text-slate-400 font-mono">#{docNumber}</p>}
        {date && (
          <p className="text-xs text-slate-400">
            {zh ? '开单日期' : 'Issued'}: <span className="text-slate-600">{date}</span>
          </p>
        )}
        {dueDate && (
          <p className="text-xs text-slate-400">
            {zh ? '到期日期' : 'Due'}: <span className="font-semibold text-slate-800">{dueDate}</span>
          </p>
        )}
      </div>
    </div>
  )
}

function ItemsTable({ items, currency, subtotal, tax, total, zh }: {
  items: QuoteOutput['items']
  currency: string
  subtotal: number
  tax?: number
  total: number
  zh: boolean
}) {
  return (
    <div>
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b-2 border-slate-200 text-left">
            <th className="pb-3 pr-4 font-semibold text-slate-600 text-xs uppercase tracking-wider w-5/12">{zh ? '项目' : 'Item'}</th>
            <th className="pb-3 pr-4 font-semibold text-slate-600 text-xs uppercase tracking-wider w-3/12 hidden sm:table-cell">{zh ? '说明' : 'Description'}</th>
            <th className="pb-3 px-2 font-semibold text-slate-600 text-xs uppercase tracking-wider text-right">{zh ? '数量' : 'Qty'}</th>
            <th className="pb-3 px-2 font-semibold text-slate-600 text-xs uppercase tracking-wider text-right">{zh ? '单价' : 'Unit Price'}</th>
            <th className="pb-3 pl-4 font-semibold text-slate-600 text-xs uppercase tracking-wider text-right">{zh ? '金额' : 'Amount'}</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-slate-100">
          {items.map((item, i) => (
            <tr key={i} className="hover:bg-slate-50/60 transition-colors">
              <td className="py-3 pr-4">
                <p className="font-medium text-slate-800">{item.name}</p>
                {item.description && <p className="text-xs text-slate-400 mt-0.5 sm:hidden">{item.description}</p>}
              </td>
              <td className="py-3 pr-4 text-slate-500 hidden sm:table-cell">{item.description}</td>
              <td className="py-3 px-2 text-right text-slate-600">{item.quantity}</td>
              <td className="py-3 px-2 text-right text-slate-600 tabular-nums">{fmt(item.unitPrice, currency)}</td>
              <td className="py-3 pl-4 text-right font-medium text-slate-800 tabular-nums">{fmt(item.amount, currency)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Totals */}
      <div className="mt-4 flex justify-end">
        <div className="w-64">
          <div className="flex justify-between py-1.5 text-sm text-slate-500 border-t border-slate-100">
            <span>{zh ? '小计' : 'Subtotal'}</span>
            <span className="tabular-nums">{fmt(subtotal, currency)}</span>
          </div>
          {tax !== undefined && tax > 0 && (
            <div className="flex justify-between py-1.5 text-sm text-slate-500">
              <span>{zh ? '税费' : 'Tax'}</span>
              <span className="tabular-nums">{fmt(tax, currency)}</span>
            </div>
          )}
          <div className="flex justify-between items-center mt-1 rounded-lg bg-slate-900 px-4 py-3 text-white">
            <span className="font-semibold text-sm">{zh ? '合计' : 'Total'}</span>
            <span className="text-lg font-bold tabular-nums">{fmt(total, currency)}</span>
          </div>
          <ExchangeRateHint amount={total} fromCurrency={currency} zh={zh} />
        </div>
      </div>
    </div>
  )
}

function TermsRow({ items }: { items: { label: string; value: string }[] }) {
  const visible = items.filter((i) => i.value)
  if (!visible.length) return null
  return (
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-5 pt-6 border-t border-slate-100">
      {visible.map(({ label, value }) => (
        <div key={label}>
          <p className="text-[10px] font-semibold text-slate-400 uppercase tracking-widest mb-1">{label}</p>
          <p className="text-sm text-slate-700">{value}</p>
        </div>
      ))}
    </div>
  )
}

function SignatureLine({ zh }: { zh: boolean }) {
  return (
    <div className="pt-10 mt-4 border-t border-slate-100 grid grid-cols-2 gap-10">
      <div>
        <div className="h-8 border-b border-slate-300" />
        <p className="mt-1.5 text-[10px] text-slate-400 uppercase tracking-widest">{zh ? '授权签字' : 'Authorized Signature'}</p>
      </div>
      <div>
        <div className="h-8 border-b border-slate-300" />
        <p className="mt-1.5 text-[10px] text-slate-400 uppercase tracking-widest">{zh ? '日期' : 'Date'}</p>
      </div>
    </div>
  )
}

function QuoteView({ data, company, zh }: { data: QuoteOutput; company: CompanyInfo | null; zh: boolean }) {
  return (
    <div className="space-y-8">
      <DocumentHeader
        company={company}
        docTitle={data.title}
        date={data.validUntil}
        zh={zh}
      />
      {data.intro && <p className="text-sm text-slate-600 leading-relaxed">{data.intro}</p>}
      <ItemsTable items={data.items} currency={data.currency} subtotal={data.subtotal} total={data.total} zh={zh} />
      <TermsRow items={[
        { label: zh ? '交付条款' : 'Delivery',      value: data.deliveryTerms },
        { label: zh ? '付款条款' : 'Payment Terms',  value: data.paymentTerms },
        { label: zh ? '有效期至' : 'Valid Until',    value: data.validUntil },
      ]} />
      {data.notes && <p className="text-sm text-slate-500 pt-4 border-t border-slate-100 leading-relaxed">{data.notes}</p>}
      <SignatureLine zh={zh} />
    </div>
  )
}

function InvoiceView({ data, company, invoiceStatus, zh }: { data: InvoiceOutput; company: CompanyInfo | null; invoiceStatus?: string | null; zh: boolean }) {
  return (
    <div className="space-y-8">
      <DocumentHeader
        company={company}
        docTitle={data.invoiceTitle}
        docNumber={data.invoiceNumber}
        date={data.issueDate}
        dueDate={data.dueDate}
        status={invoiceStatus}
        zh={zh}
      />
      {/* Parties */}
      <div className="grid grid-cols-2 gap-8">
        <div>
          <p className="text-[10px] font-semibold text-slate-400 uppercase tracking-widest mb-2">{zh ? '发票方' : 'From'}</p>
          <p className="font-semibold text-slate-800">{data.seller}</p>
        </div>
        <div>
          <p className="text-[10px] font-semibold text-slate-400 uppercase tracking-widest mb-2">{zh ? '收票方' : 'Bill To'}</p>
          <p className="font-semibold text-slate-800">{data.buyer}</p>
        </div>
      </div>
      <ItemsTable items={data.items} currency={data.currency} subtotal={data.subtotal} tax={data.tax} total={data.total} zh={zh} />
      <TermsRow items={[
        { label: zh ? '付款方式' : 'Payment Method', value: data.paymentMethod },
        { label: zh ? '付款条款' : 'Payment Terms',  value: data.paymentTerms },
      ]} />
      {data.notes && <p className="text-sm text-slate-500 pt-4 border-t border-slate-100 leading-relaxed">{data.notes}</p>}
      <SignatureLine zh={zh} />
    </div>
  )
}

function EmailView({ data, zh }: { data: EmailOutput; zh: boolean }) {
  return (
    <div className="space-y-6">
      <div className="border-b border-slate-100 pb-4">
        <p className="text-[10px] font-semibold text-slate-400 uppercase tracking-widest mb-1.5">{zh ? '主题' : 'Subject'}</p>
        <p className="font-bold text-slate-900 text-base">{data.subject}</p>
      </div>
      <div>
        <p className="text-sm text-slate-700 whitespace-pre-wrap leading-7">{data.body}</p>
      </div>
    </div>
  )
}

export default async function ViewPage({ params }: Props) {
  const { id } = await params
  const admin = createAdminClient()

  const { data: gen } = await admin
    .from('generations')
    .select('tool_type, output_data, status, locale, created_at, user_id, client_id, invoice_status, accepted_at')
    .eq('id', id)
    .single()

  if (!gen || gen.status !== 'completed' || !gen.output_data) notFound()

  const [{ data: company }] = await Promise.all([
    admin
      .from('company_profiles')
      .select('company_name, contact_name, email, phone, address, logo_url')
      .eq('user_id', gen.user_id)
      .single(),
  ])

  await admin.from('document_events').insert({
    generation_id: id,
    user_id: gen.user_id,
    client_id: (gen as { client_id?: string | null }).client_id ?? null,
    event_type: 'view',
  })

  const locale = (gen.locale as string) ?? 'en'
  const zh = locale === 'zh'

  const typeLabel: Record<string, string> = {
    quote:   zh ? '报价单' : 'Quotation',
    invoice: zh ? 'Invoice' : 'Invoice',
    email:   zh ? '商务邮件' : 'Business Email',
  }

  const toolHref: Record<string, string> = {
    quote:   `/${locale}/tools/quote`,
    invoice: `/${locale}/tools/invoice`,
    email:   `/${locale}/tools/email`,
  }

  const output = gen.output_data as QuoteOutput | InvoiceOutput | EmailOutput
  const validUntil = gen.tool_type === 'quote' ? (output as QuoteOutput).validUntil : undefined

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Top navigation bar */}
      <header className="sticky top-0 z-10 bg-white/90 backdrop-blur border-b border-slate-200">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-3 flex items-center justify-between gap-4">
          <div className="flex items-center gap-2.5">
            <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md bg-indigo-600 text-white font-bold text-sm">B</div>
            <div className="hidden sm:block">
              <p className="text-[10px] text-slate-400 uppercase tracking-widest leading-none">{zh ? '企文助手' : 'BizDoc AI'}</p>
              <p className="text-sm font-semibold text-slate-700 leading-tight">{typeLabel[gen.tool_type] ?? gen.tool_type}</p>
            </div>
          </div>
          <ViewActions id={id} zh={zh} toolHref={toolHref[gen.tool_type] ?? `/${locale}`} zh_label={zh} />
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-8 space-y-5">
        {/* Validity warning */}
        {validUntil && <ValidityBanner validUntil={validUntil} zh={zh} />}

        {/* Document card */}
        <div className="relative bg-white rounded-2xl shadow-md overflow-hidden">
          {/* Top accent bar */}
          <div className="h-1.5 bg-gradient-to-r from-indigo-500 via-indigo-600 to-violet-600" />

          <div className="px-8 sm:px-12 py-10">
            {gen.tool_type === 'quote'   && <QuoteView   data={output as QuoteOutput}   company={company} zh={zh} />}
            {gen.tool_type === 'invoice' && <InvoiceView data={output as InvoiceOutput} company={company} invoiceStatus={gen.invoice_status} zh={zh} />}
            {gen.tool_type === 'email'   && <EmailView   data={output as EmailOutput}   zh={zh} />}
          </div>

          {/* Footer inside card */}
          <div className="px-8 sm:px-12 py-4 bg-slate-50/60 border-t border-slate-100 flex items-center justify-between gap-4">
            <p className="text-xs text-slate-400">
              {zh ? '此文书由企文助手 AI 生成' : 'Generated with BizDoc AI'}
            </p>
            <p className="text-xs text-slate-300 font-mono hidden sm:block select-all break-all">
              {`${process.env.NEXT_PUBLIC_SITE_URL ?? ''}/view/${id}`}
            </p>
          </div>
        </div>

        {/* Accept quote */}
        {gen.tool_type === 'quote' && !gen.accepted_at && (
          <QuoteAcceptButton genId={id} zh={zh} />
        )}
        {gen.tool_type === 'quote' && gen.accepted_at && (
          <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-center space-y-1">
            <p className="text-emerald-700 font-semibold">✅ {zh ? '此报价单已被接受' : 'Quote Accepted'}</p>
            <p className="text-sm text-emerald-600">
              {zh ? `接受时间：${new Date(gen.accepted_at as string).toLocaleDateString('zh-CN')}` : `Accepted on ${new Date(gen.accepted_at as string).toLocaleDateString('en-US')}`}
            </p>
          </div>
        )}

        {/* CTA card */}
        <div className="rounded-2xl border border-indigo-100 bg-white px-6 py-5 flex flex-col sm:flex-row items-center justify-between gap-4 shadow-sm">
          <div>
            <p className="font-semibold text-slate-800 text-sm">{zh ? '也想生成这样的专业文书？' : 'Need a professional document like this?'}</p>
            <p className="text-xs text-slate-400 mt-0.5">{zh ? '免费使用，无需信用卡' : 'Free to use — no credit card needed'}</p>
          </div>
          <a
            href={toolHref[gen.tool_type] ?? `/${locale}`}
            className="shrink-0 rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700 transition-colors shadow-sm"
          >
            {zh ? '免费生成我的文书 →' : 'Create mine — Free →'}
          </a>
        </div>
      </main>
    </div>
  )
}
