import { notFound } from 'next/navigation'
import { isValidLocale } from '@/lib/i18n'
import type { Metadata } from 'next'

type Props = { params: Promise<{ locale: string }> }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params
  return {
    title: locale === 'zh' ? '服务条款 | 企文助手' : 'Terms of Service | BizDoc AI',
  }
}

export default async function TermsPage({ params }: Props) {
  const { locale } = await params
  if (!isValidLocale(locale)) notFound()
  const zh = locale === 'zh'

  return (
    <div className="max-w-3xl mx-auto px-4 py-16">
      <h1 className="text-3xl font-bold text-gray-900 mb-2">
        {zh ? '服务条款' : 'Terms of Service'}
      </h1>
      <p className="text-sm text-gray-400 mb-10">
        {zh ? '最后更新：2025 年 5 月' : 'Last updated: May 2025'}
      </p>

      <div className="space-y-8 text-sm text-gray-700 leading-relaxed">

        <section>
          <h2 className="text-lg font-semibold text-gray-900 mb-3">
            {zh ? '1. 服务说明' : '1. Service Description'}
          </h2>
          <p>
            {zh
              ? '企文助手是一款面向小企业和自由职业者的 AI 文书生成工具，提供报价单、Invoice 和商务邮件的自动生成功能。使用本服务即表示您接受以下条款。'
              : 'BizDoc AI is an AI-powered document generation tool for small businesses and freelancers, providing automated quote, invoice, and business email generation. Using the Service constitutes acceptance of these terms.'}
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 mb-3">
            {zh ? '2. 账户与配额' : '2. Account & Quota'}
          </h2>
          <ul className="list-disc pl-5 space-y-2">
            <li>
              {zh
                ? '免费版：每月 5 次生成，PDF 含水印，历史记录最近 3 条'
                : 'Free plan: 5 generations per month, watermarked PDF exports, last 3 history records'}
            </li>
            <li>
              {zh
                ? 'Pro 版：每月 100 次生成，无水印 PDF，完整历史记录'
                : 'Pro plan: 100 generations per month, watermark-free PDF, full history'}
            </li>
            <li>
              {zh
                ? '企业版：每月 500 次生成，完整历史记录，无水印 PDF'
                : 'Business plan: 500 generations per month, full history, watermark-free PDF'}
            </li>
            <li>
              {zh
                ? '配额每月自动重置，未使用次数不累计至下月'
                : 'Quota resets monthly; unused generations do not carry over'}
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 mb-3">
            {zh ? '3. 付款与退款' : '3. Payment & Refunds'}
          </h2>
          <p className="mb-3">
            {zh
              ? '目前通过微信、支付宝或 PayPal 手动升级。付款后请联系客服并提供注册邮箱，客服将在 24 小时内为您开通。'
              : 'Upgrades are currently processed manually via WeChat Pay, Alipay, or PayPal. After payment, contact support with your registered email and we will activate your plan within 24 hours.'}
          </p>
          <p>
            {zh
              ? '如对服务不满意，可在首次付款后 7 天内申请全额退款，无需说明理由。'
              : 'If you are unsatisfied with the Service, you may request a full refund within 7 days of your first payment, no questions asked.'}
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 mb-3">
            {zh ? '4. 可接受使用' : '4. Acceptable Use'}
          </h2>
          <p className="mb-3">{zh ? '您同意不将本服务用于：' : 'You agree not to use the Service to:'}</p>
          <ul className="list-disc pl-5 space-y-2">
            <li>{zh ? '生成虚假、欺诈性的商业文书' : 'Generate false or fraudulent business documents'}</li>
            <li>{zh ? '违反任何适用法律法规的用途' : 'Violate any applicable laws or regulations'}</li>
            <li>{zh ? '通过自动化手段大量滥用 API 或绕过配额限制' : 'Abuse the API at scale or circumvent quota limits through automation'}</li>
            <li>{zh ? '向第三方转售本服务的生成能力' : "Resell the Service's generation capacity to third parties"}</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 mb-3">
            {zh ? '5. 知识产权' : '5. Intellectual Property'}
          </h2>
          <p>
            {zh
              ? '您对使用本服务生成的文书内容拥有完整权利，可自由用于商业目的。企文助手的品牌、界面设计和底层代码归本产品所有。'
              : 'You retain full rights to the documents generated using the Service and may use them freely for commercial purposes. The BizDoc AI brand, UI design, and underlying code remain the property of the Service.'}
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 mb-3">
            {zh ? '6. 免责声明' : '6. Disclaimer'}
          </h2>
          <p>
            {zh
              ? '本产品生成的文书仅供参考，不构成法律、财务或税务建议。请在使用前根据实际情况核实内容的准确性。本产品对因使用生成内容而产生的任何损失不承担责任。'
              : 'Documents generated by the Service are for reference only and do not constitute legal, financial, or tax advice. Please verify accuracy before use. The Service is not liable for any losses arising from the use of generated content.'}
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 mb-3">
            {zh ? '7. 服务变更与终止' : '7. Changes & Termination'}
          </h2>
          <p>
            {zh
              ? '我们保留随时修改服务功能或价格的权利，并会通过邮件提前通知付费用户。您可随时取消账户。'
              : 'We reserve the right to modify features or pricing at any time and will notify paid users by email in advance. You may cancel your account at any time.'}
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 mb-3">
            {zh ? '8. 联系我们' : '8. Contact'}
          </h2>
          <p>
            {zh ? '如有任何问题，请联系：' : 'For any questions, contact:'}
            {' '}
            <a href="mailto:fanhui100@gmail.com" className="text-primary hover:underline">
              fanhui100@gmail.com
            </a>
          </p>
        </section>

      </div>
    </div>
  )
}
